[text]
AppTitle = "Windows NT Task Manager"
RunTitle = "Run"
RunPrompt = "Type the name of a program, folder, document, or Internet resource, and Windows will open it for you."
ApplicationsPageTitle = "Applications"
ProcessesPageTitle = "Processes"
PerformancePageTitle = "Performance"
NetworkingPageTitle = "Networking"
UsersPageTitle = "Users"
TaskManagerDisabled = "Task Manager has been disabled by your administrator."
WarningTitle = "Task Manager Warning"
PriorityChangeWarning = """WARNING: Changing the priority class of this process may
cause undesired results including system instability.  Are you
sure you want to change the priority class?"""
KillProcessWarning = """WARNING: Terminating a process can cause undesired
results including loss of data and system instability.  The
process will not be given the chance to save its state or
data before it is terminated.  Are you sure you want to
terminate the process?"""
DebugProcessWarning = """WARNING: Debugging this process may result in loss of data.
Are you sure you wish to attach the debugger?"""
InvalidOptionTitle = "Invalid Option"
NoAffinityMaskMessage = "The process must have affinity with at least one processor."
UnableToTerminateProcess = "Unable to Terminate Process"
UnableToAttachDebugger = "Unable to Attach Debugger"
UnableToChangePriority = "Unable to Change Priority"
UnableToSetAffinity = """The operation could not be completed.

"""
FormatProcesses = "Processes: %d"
FormatCpuUsage = "CPU Usage: %d%%"
FormatMemoryUsage = "Mem Usage: %dK / %dK"
FormatCpuNumber = "CPU %d"
TotalCpu = "Total CPU"
KernelCpu = "Kernel CPU"
TaskColumnTask = "Task"
TaskColumnStatus = "Status"
TaskColumnWinstation = "WinStation"
TaskColumnDesktop = "Desktop"
ProcessColumnImageName = "Image Name"
ProcessColumnPid = "PID"
ProcessColumnCpu = "CPU"
ProcessColumnCpuTime = "CPU Time"
ProcessColumnMemoryUsage = "Mem Usage"
ProcessColumnMemoryUsageDelta = "Mem Delta"
ProcessColumnPageFaults = "Page Faults"
ProcessColumnPageFaultsDelta = "PF Delta"
ProcessColumnVirtualMemorySize = "VM Size"
ProcessColumnPagedPool = "Paged Pool"
ProcessColumnNonPagedPool = "NP Pool"
ProcessColumnBasePriority = "Base Pri"
ProcessColumnHandleCount = "Handles"
ProcessColumnThreadCount = "Threads"
ProcessColumnSessionId = "Session ID"
ProcessColumnUserName = "User Name"
File = "&File"
Options = "&Options"
View = "&View"
Windows = "&Windows"
Help = "&Help"
UpdateSpeed = "&Update Speed"
CpuHistory = "&CPU History"
NewTaskMenu = "&Run..."
NewTaskButton = "&Run..."
ExitTaskManager = "E&xit Task Manager"
AlwaysOnTop = "&Always On Top"
MinimizeOnUse = "&Minimize On Use"
Confirmations = "&Confirmations"
HideWhenMinimized = "&Hide When Minimized"
RefreshNow = "&Refresh Now"
High = "&High"
Normal = "&Normal"
Low = "&Low"
Paused = "&Paused"
LargeIcons = "Lar&ge Icons"
SmallIcons = "S&mall Icons"
Details = "&Details"
TileHorizontally = "Tile &Horizontally"
TileVertically = "Tile &Vertically"
Minimize = "&Minimize"
Maximize = "Ma&ximize"
Cascade = "&Cascade"
BringToFront = "&Bring to Front"
HelpTopics = "Task Manager &Help Topics"
AboutTaskManager = "&About Task Manager"
OneGraphAllCpus = "One Graph, &All CPUs"
OneGraphPerCpu = "One Graph &Per CPU"
SelectColumnsMenu = "Select &Columns..."
SelectColumnsTitle = "Select Columns"
SelectProcessColumnsDescription = "Select the columns that will appear on the Process page of the Task Manager."
ShowKernelTimes = "Show &Kernel Times"
RestoreTaskManager = "&Restore Task Manager"
EndProcess = "&End Process"
EndProcessTree = "End Process &Tree"
OpenFileLocation = "Open File &Location"
Debug = "&Debug"
SetPriority = "Set &Priority"
Realtime = "&Realtime"
AboveNormal = "&Above Normal"
BelowNormal = "&Below Normal"
SetAffinity = "Set &Affinity..."
SwitchTo = "&Switch To"
EndTask = "&End Task"
GoToProcess = "&Go To Process"
Disconnect = "&Disconnect"
Logoff = "&Logoff"
SendMessage = "&Send Message..."
SendMessageTitle = "Send Message"
TaskManager = "Task Manager"
Handles = "Handles"
Threads = "Threads"
ProcessesLabel = "Processes"
CpuUsageHistory = "CPU Usage History"
CpuUsage = "CPU Usage"
MemUsage = "MEM Usage"
MemoryUsageHistory = "Memory Usage History"
PhysicalMemoryK = "Physical Memory (K)"
CommitChargeK = "Commit Charge (K)"
KernelMemoryK = "Kernel Memory (K)"
Totals = "Totals"
Total = "Total"
Available = "Available"
FileCache = "File Cache"
Paged = "Paged"
Nonpaged = "Nonpaged"
Limit = "Limit"
Peak = "Peak"
NoActiveNetworkAdaptersFound = "No Active Network Adapters Found."
Ok = "OK"
Cancel = "Cancel"
ImageName = "&Image Name"
PidProcessIdentifier = "PID (Process Identifier)"
UserName = "User Name"
SessionId = "Session ID"
CpuTime = "CPU Time"
MemoryUsage = "Memory Usage"
MemoryUsageDelta = "Memory Usage Delta"
PageFaults = "Page Faults"
PageFaultsDelta = "Page Faults Delta"
VirtualMemorySize = "Virtual Memory Size"
PagedPool = "Paged Pool"
NonPagedPool = "Non-paged Pool"
BasePriority = "Base Priority"
HandleCount = "Handle Count"
ThreadCount = "Thread Count"
ProcessorAffinity = "Processor Affinity"
Processors = "Processors"
ProcessorAffinityDescription = "The Processor Affinity setting controls which CPUs the process will be allowed to execute on."
MessageTitleLabel = "&Message title:"
MessageLabel = "Me&ssage:"
ShowFullAccountName = "&Show Full Account Name"
User = "User"
Status = "Status"
ClientName = "Client Name"
Session = "Session"
Adapter = "Adapter"
NetworkUtilization = "Network Utilization"
LinkSpeed = "Link Speed"
State = "State"
BytesSent = "Bytes Sent"
BytesReceived = "Bytes Received"
BytesTotal = "Bytes Total"
Connected = "Connected"
Disconnected = "Disconnected"
Connecting = "Connecting"
Disconnecting = "Disconnecting"
HardwareMissing = "Hardware Missing"
HardwareDisabled = "Hardware Disabled"
HardwareMalfunction = "Hardware Malfunction"
Unknown = "Unknown"
Active = "Active"
ConnectQuery = "Connect Query"
Shadow = "Shadow"
Idle = "Idle"
Listening = "Listening"
Reset = "Reset"
Down = "Down"
Init = "Init"
Bitness32Suffix = "(32-bit)"
NotResponding = "Not Responding"
Running = "Running"
MessageCouldNotBeSent = "The message could not be sent."
UnableToOpenFileLocation = "Unable to Open File Location"
KillProcessTreePrompt = """This operation will attempt to terminate this process and any
processes which were directly or indirectly started by it.

Forcing processes to terminate in this manner can cause
data loss and system instability.

Are you sure you wish to continue?"""
KillProcessTreeFailed = "Unable to Completely End the Process Tree"
KillProcessTreeFailedBody = """One or more of the processes in this process tree could not
be ended. The operation was not fully successful."""
ConfirmLogoffSelectedUsers = "Are you sure you want to logoff the selected user(s)?"
ConfirmDisconnectSelectedUsers = "Are you sure you want to disconnect the selected user(s)?"
SelectedUserCouldNotBeLoggedOff = "The selected user could not be logged off."
SelectedUserCouldNotBeDisconnected = "The selected user could not be disconnected."
Win32ErrorPrefix = "Win32 error:"

[menu_status_help]
IDM_RUN = "Runs a new program"
IDM_EXIT = "Exits the Task Manager application"
IDM_ALWAYSONTOP = "Task Manager remains in front of all other windows unless minimized"
IDM_MINIMIZEONUSE = "Task Manager is minimized when a SwitchTo operation is performed"
IDM_LARGEICONS = "Displays tasks by using large icons"
IDM_SMALLICONS = "Displays tasks by using small icons"
IDM_DETAILS = "Displays information about each task"
IDM_ALLCPUS = "A single history graph shows total CPU usage"
IDM_MULTIGRAPH = "Each CPU has its own history graph"
IDM_ABOUT = "Displays program information, version number, and copyright"
IDM_HIGH = "Updates the display twice per second"
IDM_NORMAL = "Updates the display every two seconds"
IDM_LOW = "Updates the display every four seconds"
IDM_PAUSED = "Display does not automatically update"
IDM_CONFIRMATIONS = "Task Manager will prompt before modifying processes"
IDM_PROC_DEBUG = "Attaches the debugger to this process"
IDM_PROC_TERMINATE = "Removes the process from the system"
IDM_PROC_ENDTREE = "Removes the process and any child processes from the system"
IDM_HELP = "Displays Task Manager help topics"
IDM_PROCCOLS = "Select which columns will be visible on the Process page"
IDM_REFRESH = "Force Task Manager to update now, regardless of Update Speed setting"
IDM_AFFINITY = "Controls which processors the process will be allowed to run on"
IDM_KERNELTIMES = "Displays kernel timings on the CPU graphs in red."
IDM_TASK_MINIMIZE = "Minimizes the windows"
IDM_TASK_MAXIMIZE = "Maximizes the windows"
IDM_TASK_CASCADE = "Cascades the windows diagonally on the desktop"
IDM_TASK_TILEHORZ = "Tiles the windows horizontally on the desktop"
IDM_TASK_TILEVERT = "Tiles the windows vertically on the desktop"
IDM_TASK_BRINGTOFRONT = "Brings the window front, but does not switch to it"
