[text]
AppTitle = "Administrador de tareas de Windows NT"
RunTitle = "Ejecutar"
RunPrompt = "Escriba el nombre de un programa, carpeta, documento o recurso de Internet, y Windows lo abrirá por usted."
ApplicationsPageTitle = "Aplicaciones"
ProcessesPageTitle = "Procesos"
PerformancePageTitle = "Rendimiento"
NetworkingPageTitle = "Red"
UsersPageTitle = "Usuarios"
TaskManagerDisabled = "El Administrador de tareas ha sido deshabilitado por su administrador."
WarningTitle = "Advertencia del Administrador de tareas"
PriorityChangeWarning = "ADVERTENCIA: Cambiar la clase de prioridad de este proceso puede causar resultados no deseados, incluida la inestabilidad del sistema. ¿Seguro que desea cambiar la clase de prioridad?"
KillProcessWarning = "ADVERTENCIA: Finalizar un proceso puede causar resultados no deseados, incluida la pérdida de datos y la inestabilidad del sistema. El proceso no tendrá oportunidad de guardar su estado o sus datos antes de ser finalizado. ¿Seguro que desea finalizar este proceso?"
DebugProcessWarning = "ADVERTENCIA: Depurar este proceso puede causar pérdida de datos. ¿Seguro que desea adjuntar el depurador?"
InvalidOptionTitle = "Opción no válida"
NoAffinityMaskMessage = "El proceso debe tener afinidad con al menos un procesador."
UnableToTerminateProcess = "No se pudo finalizar el proceso"
UnableToAttachDebugger = "No se pudo adjuntar el depurador"
UnableToChangePriority = "No se pudo cambiar la prioridad"
UnableToSetAffinity = """No se pudo completar la operación.

"""
FormatProcesses = "Procesos: %d"
FormatCpuUsage = "Uso de CPU: %d%%"
FormatMemoryUsage = "Uso de memoria: %dK / %dK"
FormatCpuNumber = "CPU %d"
TotalCpu = "CPU total"
KernelCpu = "CPU del núcleo"
TaskColumnTask = "Tarea"
TaskColumnStatus = "Estado"
TaskColumnWinstation = "Estación Win"
TaskColumnDesktop = "Escritorio"
ProcessColumnImageName = "Nombre de imagen"
ProcessColumnPid = "PID"
ProcessColumnCpu = "CPU"
ProcessColumnCpuTime = "Tiempo de CPU"
ProcessColumnMemoryUsage = "Uso de memoria"
ProcessColumnMemoryUsageDelta = "Delta de memoria"
ProcessColumnPageFaults = "Errores de página"
ProcessColumnPageFaultsDelta = "Delta de errores de página"
ProcessColumnVirtualMemorySize = "Tamaño de memoria virtual"
ProcessColumnPagedPool = "Bloque paginado"
ProcessColumnNonPagedPool = "Bloque no paginado"
ProcessColumnBasePriority = "Prioridad base"
ProcessColumnHandleCount = "Handles"
ProcessColumnThreadCount = "Hilos"
ProcessColumnSessionId = "Id. de sesión"
ProcessColumnUserName = "Nombre de usuario"
File = "&Archivo"
Options = "&Opciones"
View = "&Ver"
Windows = "&Ventanas"
Help = "Ay&uda"
UpdateSpeed = "&Velocidad de actualización"
CpuHistory = "&Historial de CPU"
NewTaskMenu = "&Ejecutar..."
NewTaskButton = "&Ejecutar..."
ExitTaskManager = "&Salir del Administrador de tareas"
AlwaysOnTop = "&Siempre visible"
MinimizeOnUse = "&Minimizar al usar"
Confirmations = "&Confirmaciones"
HideWhenMinimized = "&Ocultar al minimizar"
RefreshNow = "&Actualizar ahora"
High = "&Alta"
Normal = "&Normal"
Low = "&Baja"
Paused = "&Pausado"
LargeIcons = "Iconos &grandes"
SmallIcons = "Iconos &pequeños"
Details = "&Detalles"
TileHorizontally = "Mosaico &horizontal"
TileVertically = "Mosaico &vertical"
Minimize = "&Minimizar"
Maximize = "Ma&ximizar"
Cascade = "&Cascada"
BringToFront = "Traer al &frente"
HelpTopics = "Temas de a&yuda del Administrador de tareas"
AboutTaskManager = "&Acerca del Administrador de tareas"
OneGraphAllCpus = "Un gráfico, &todas las CPU"
OneGraphPerCpu = "Un gráfico &por CPU"
SelectColumnsMenu = "Seleccionar columnas..."
SelectColumnsTitle = "Seleccionar columnas"
SelectProcessColumnsDescription = "Seleccione las columnas que aparecerán en la pestaña Procesos del Administrador de tareas."
ShowKernelTimes = "Mostrar tiempos del &núcleo"
RestoreTaskManager = "&Restaurar el Administrador de tareas"
EndProcess = "&Finalizar proceso"
EndProcessTree = "End Process &Tree"
OpenFileLocation = "Open File &Location"
Debug = "&Depurar"
SetPriority = "Establecer &prioridad"
Realtime = "&Tiempo real"
AboveNormal = "&Above Normal"
BelowNormal = "&Below Normal"
SetAffinity = "Establecer a&finidad..."
SwitchTo = "&Cambiar a"
EndTask = "&Finalizar tarea"
GoToProcess = "&Ir al proceso"
Disconnect = "&Desconectar"
Logoff = "Ce&rrar sesión"
SendMessage = "&Enviar mensaje..."
SendMessageTitle = "Enviar mensaje"
TaskManager = "Administrador de tareas"
Handles = "Handles"
Threads = "Hilos"
ProcessesLabel = "Procesos"
CpuUsageHistory = "Historial de uso de CPU"
CpuUsage = "Uso de CPU"
MemUsage = "Uso de memoria"
MemoryUsageHistory = "Historial de uso de memoria"
PhysicalMemoryK = "Memoria física (K)"
CommitChargeK = "Memoria confirmada (K)"
KernelMemoryK = "Memoria del núcleo (K)"
Totals = "Totales"
Total = "Total"
Available = "Disponible"
FileCache = "Caché de archivos"
Paged = "Paginado"
Nonpaged = "No paginado"
Limit = "Límite"
Peak = "Pico"
NoActiveNetworkAdaptersFound = "No se encontraron adaptadores de red activos."
Ok = "Aceptar"
Cancel = "Cancelar"
ImageName = "Nombre de imagen"
PidProcessIdentifier = "PID (identificador de proceso)"
UserName = "Nombre de usuario"
SessionId = "Id. de sesión"
CpuTime = "Tiempo de CPU"
MemoryUsage = "Uso de memoria"
MemoryUsageDelta = "Delta de uso de memoria"
PageFaults = "Errores de página"
PageFaultsDelta = "Delta de errores de página"
VirtualMemorySize = "Tamaño de memoria virtual"
PagedPool = "Bloque paginado"
NonPagedPool = "Bloque no paginado"
BasePriority = "Prioridad base"
HandleCount = "Número de handles"
ThreadCount = "Número de hilos"
ProcessorAffinity = "Afinidad del procesador"
Processors = "Procesadores"
ProcessorAffinityDescription = "La configuracion de afinidad del procesador controla en que CPU se permitira ejecutar el proceso."
MessageTitleLabel = "Título del mensaje:"
MessageLabel = "Mensaje:"
ShowFullAccountName = "Mostrar nombre completo de la cuenta"
User = "Usuario"
Status = "Estado"
ClientName = "Nombre del cliente"
Session = "Sesión"
Adapter = "Adaptador"
NetworkUtilization = "Utilizacion de red"
LinkSpeed = "Velocidad del vinculo"
State = "Estado"
BytesSent = "Bytes enviados"
BytesReceived = "Bytes recibidos"
BytesTotal = "Bytes totales"
Connected = "Conectado"
Disconnected = "Desconectado"
Connecting = "Conectando"
Disconnecting = "Desconectando"
HardwareMissing = "Hardware ausente"
HardwareDisabled = "Hardware deshabilitado"
HardwareMalfunction = "Fallo de hardware"
Unknown = "Desconocido"
Active = "Activo"
ConnectQuery = "Consulta de conexión"
Shadow = "Sombra"
Idle = "Inactivo"
Listening = "Escuchando"
Reset = "Restablecer"
Down = "Inactivo"
Init = "Inicializando"
Bitness32Suffix = "(32 bits)"
NotResponding = "No responde"
Running = "En ejecucion"
MessageCouldNotBeSent = "No se pudo enviar el mensaje."
UnableToOpenFileLocation = "Unable to Open File Location"
KillProcessTreePrompt = """This operation will attempt to terminate this process and any
processes which were directly or indirectly started by it.

Forcing processes to terminate in this manner can cause
data loss and system instability.

Are you sure you wish to continue?"""
KillProcessTreeFailed = "Unable to Completely End the Process Tree"
KillProcessTreeFailedBody = """One or more of the processes in this process tree could not
be ended. The operation was not fully successful."""
ConfirmLogoffSelectedUsers = "¿Seguro que desea cerrar la sesion de los usuarios seleccionados?"
ConfirmDisconnectSelectedUsers = "¿Seguro que desea desconectar a los usuarios seleccionados?"
SelectedUserCouldNotBeLoggedOff = "No se pudo cerrar la sesion del usuario seleccionado."
SelectedUserCouldNotBeDisconnected = "No se pudo desconectar al usuario seleccionado."
Win32ErrorPrefix = "Error de Win32:"

[menu_status_help]
IDM_RUN = "Runs a new program"
IDM_EXIT = "Exits the Task Manager application"
IDM_ALWAYSONTOP = "Task Manager remains in front of all other windows unless minimized"
IDM_MINIMIZEONUSE = "Task Manager is minimized when a SwitchTo operation is performed"
IDM_LARGEICONS = "Displays tasks by using large icons"
IDM_SMALLICONS = "Displays tasks by using small icons"
IDM_DETAILS = "Displays information about each task"
IDM_ALLCPUS = "A single history graph shows total CPU usage"
IDM_MULTIGRAPH = "Each CPU has its own history graph"
IDM_ABOUT = "Displays program information, version number, and copyright"
IDM_HIGH = "Updates the display twice per second"
IDM_NORMAL = "Updates the display every two seconds"
IDM_LOW = "Updates the display every four seconds"
IDM_PAUSED = "Display does not automatically update"
IDM_CONFIRMATIONS = "Task Manager will prompt before modifying processes"
IDM_PROC_DEBUG = "Attaches the debugger to this process"
IDM_PROC_TERMINATE = "Removes the process from the system"
IDM_PROC_ENDTREE = "Removes the process and any child processes from the system"
IDM_HELP = "Displays Task Manager help topics"
IDM_PROCCOLS = "Select which columns will be visible on the Process page"
IDM_REFRESH = "Force Task Manager to update now, regardless of Update Speed setting"
IDM_AFFINITY = "Controls which processors the process will be allowed to run on"
IDM_KERNELTIMES = "Displays kernel timings on the CPU graphs in red."
IDM_TASK_MINIMIZE = "Minimizes the windows"
IDM_TASK_MAXIMIZE = "Maximizes the windows"
IDM_TASK_CASCADE = "Cascades the windows diagonally on the desktop"
IDM_TASK_TILEHORZ = "Tiles the windows horizontally on the desktop"
IDM_TASK_TILEVERT = "Tiles the windows vertically on the desktop"
IDM_TASK_BRINGTOFRONT = "Brings the window front, but does not switch to it"
